feat: Change request to axios
enquirer/prompt-google-form pull request #5
Opened 2020-01-15 18:18 UTC by adityavyas611

**Please check if the PR fulfills these requirements**

- [x] The commit message follows our guidelines
- [x] Change request module to Axios module as per standard

**What kind of change does this PR introduce?**

- In these pull request, I have changed the request module to Axios module

**What is the new behavior?**

- The request has been sent through Axios.

Fixes: #4

2020-01-17 00:39 UTC, doowb requested changes
Thanks for the PR! There are a couple of things to change (linting and a variable name).

2020-01-17 00:39 UTC, doowb commented on lib/loadQuestions.js
> +}
Missing `;`

```suggestion
};
```

2020-01-17 00:39 UTC, doowb commented on lib/loadQuestions.js
> +  const body = await axios({
use `res` instead of `body`:

```suggestion
  const res = await axios({
```

2020-01-17 00:39 UTC, doowb commented on lib/loadQuestions.js
> +  const questions = await parse(body.data);
use `res` instead of `body`:

```suggestion
  const questions = await parse(res.data);
```

2020-01-26 20:03 UTC, adityavyas611 commented
Hi @doowb, Could you please review this and merge?

2022-09-10 18:38 UTC, merged